import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import {
  Search,
  MapPin,
  Plane,
  Users,
  Star,
  TrendingUp,
  Globe,
  Calendar,
  Heart,
  ArrowRight,
  Sparkles,
  Shield,
  Clock,
  Award,
} from 'lucide-react';

import Layout from '@/components/layout/Layout';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
import DestinationCard from '@/components/destinations/DestinationCard';
import { LoadingSpinner, DestinationCardSkeleton } from '@/components/ui/Loading';
import { useAuthStore } from '@/services/auth';
import { destinationService, useFavorites } from '@/services/destinations';
import { tripService, useTripStats } from '@/services/trips';
import { Destination } from '@/utils/types';

const HomePage: React.FC = () => {
  const [popularDestinations, setPopularDestinations] = useState<Destination[]>([]);
  const [isLoadingDestinations, setIsLoadingDestinations] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const router = useRouter();
  
  const { isAuthenticated, user } = useAuthStore();
  const { favorites, toggleFavorite } = useFavorites();
  const { stats } = useTripStats();

  useEffect(() => {
    loadPopularDestinations();
  }, []);

  const loadPopularDestinations = async () => {
    try {
      const destinations = await destinationService.getPopularDestinations(6);
      setPopularDestinations(destinations);
    } catch (error) {
      console.error('Failed to load destinations:', error);
    } finally {
      setIsLoadingDestinations(false);
    }
  };

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (searchQuery.trim()) {
      router.push(`/destinations?search=${encodeURIComponent(searchQuery.trim())}`);
    }
  };

  const handleFavoriteToggle = async (destinationId: number, isFavorite: boolean) => {
    if (!isAuthenticated) {
      router.push('/auth/login');
      return;
    }
    
    try {
      await toggleFavorite(destinationId);
    } catch (error) {
      console.error('Failed to toggle favorite:', error);
    }
  };

  const features = [
    {
      icon: Sparkles,
      title: 'AI-Powered Itineraries',
      description: 'Get personalized day-by-day plans generated by advanced AI',
      color: 'text-purple-600',
      bg: 'bg-purple-100',
    },
    {
      icon: Globe,
      title: 'Global Destinations',
      description: 'Explore thousands of destinations worldwide with detailed information',
      color: 'text-blue-600',
      bg: 'bg-blue-100',
    },
    {
      icon: Shield,
      title: 'Real-time Weather',
      description: 'Stay updated with current weather conditions at your destinations',
      color: 'text-green-600',
      bg: 'bg-green-100',
    },
    {
      icon: Calendar,
      title: 'Trip Management',
      description: 'Organize all your trips in one place with smart scheduling',
      color: 'text-orange-600',
      bg: 'bg-orange-100',
    },
  ];

  const testimonials = [
    {
      name: 'Sarah Johnson',
      location: 'New York, USA',
      text: 'WanderMind helped me plan the perfect 2-week European adventure. The AI itinerary was spot-on!',
      rating: 5,
      avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=64&h=64&fit=crop&crop=face',
    },
    {
      name: 'Ahmed Hassan',
      location: 'Dubai, UAE',
      text: 'The currency converter and weather updates made my business trips so much easier to plan.',
      rating: 5,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=64&h=64&fit=crop&crop=face',
    },
    {
      name: 'Maria Garcia',
      location: 'Madrid, Spain',
      text: 'I love how I can save my favorite destinations and get personalized recommendations.',
      rating: 5,
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=64&h=64&fit=crop&crop=face',
    },
  ];

  const stats_display = [
    { label: 'Happy Travelers', value: '50,000+', icon: Users },
    { label: 'Destinations', value: '1,200+', icon: MapPin },
    { label: 'Countries', value: '150+', icon: Globe },
    { label: 'AI Itineraries', value: '25,000+', icon: Sparkles },
  ];

  return (
    <Layout
      title="WanderMind - Your Intelligent Travel Companion"
      description="Plan your perfect trip with AI-powered itineraries, discover amazing destinations, and manage your travel experiences all in one place."
    >
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-gradient-to-br from-primary-600 via-travel-600 to-purple-700">
        <div className="absolute inset-0 bg-black/20"></div>
        <div className="absolute inset-0 bg-gradient-to-r from-blue-600/20 to-purple-600/20"></div>
        
        {/* Background Pattern */}
        <div className="absolute inset-0 opacity-10">
          <div className="absolute top-0 left-0 w-full h-full"
               style={{
                 backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.1'%3E%3Ccircle cx='30' cy='30' r='1'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`,
               }}
          />
        </div>

        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 lg:py-32">
          <div className="text-center">
            <div className="flex items-center justify-center space-x-2 mb-6">
              <div className="bg-white/20 backdrop-blur-sm p-3 rounded-2xl">
                <Plane className="h-8 w-8 text-white" />
              </div>
              <h1 className="text-4xl lg:text-6xl font-bold text-white">
                WanderMind
              </h1>
            </div>
            
            <h2 className="text-xl lg:text-2xl text-blue-100 mb-8 max-w-3xl mx-auto leading-relaxed">
              Your Intelligent Travel Companion for Unforgettable Journeys
            </h2>
            
            <p className="text-lg text-blue-100 mb-12 max-w-2xl mx-auto">
              Discover amazing destinations, create AI-powered itineraries, and manage all your travels in one smart platform.
            </p>

            {/* Search Bar */}
            <form onSubmit={handleSearch} className="max-w-2xl mx-auto mb-12">
              <div className="relative">
                <Input
                  type="text"
                  placeholder="Where do you want to go? (e.g., Paris, Tokyo, New York)"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-12 pr-32 py-4 text-lg bg-white/95 backdrop-blur-sm border-0 shadow-xl"
                  icon={Search}
                />
                <Button
                  type="submit"
                  variant="primary"
                  size="lg"
                  className="absolute right-2 top-2"
                >
                  Explore
                </Button>
              </div>
            </form>

            {/* CTA Buttons */}
            <div className="flex flex-col sm:flex-row items-center justify-center space-y-4 sm:space-y-0 sm:space-x-6">
              {isAuthenticated ? (
                <>
                  <Link href="/trips">
                    <Button variant="secondary" size="lg" icon={Calendar}>
                      View My Trips
                    </Button>
                  </Link>
                  <Link href="/destinations">
                    <Button variant="outline" size="lg" className="bg-white/10 border-white/20 text-white hover:bg-white/20">
                      Explore Destinations
                    </Button>
                  </Link>
                </>
              ) : (
                <>
                  <Link href="/auth/register">
                    <Button variant="secondary" size="lg" icon={ArrowRight}>
                      Get Started Free
                    </Button>
                  </Link>
                  <Link href="/destinations">
                    <Button variant="outline" size="lg" className="bg-white/10 border-white/20 text-white hover:bg-white/20">
                      Explore Destinations
                    </Button>
                  </Link>
                </>
              )}
            </div>

            {/* User Stats (if authenticated) */}
            {isAuthenticated && stats && (
              <div className="mt-12 grid grid-cols-2 md:grid-cols-4 gap-6 max-w-2xl mx-auto">
                <div className="bg-white/10 backdrop-blur-sm rounded-xl p-4">
                  <div className="text-2xl font-bold text-white">{stats.totalTrips}</div>
                  <div className="text-blue-100 text-sm">Total Trips</div>
                </div>
                <div className="bg-white/10 backdrop-blur-sm rounded-xl p-4">
                  <div className="text-2xl font-bold text-white">{stats.upcomingTrips}</div>
                  <div className="text-blue-100 text-sm">Upcoming</div>
                </div>
                <div className="bg-white/10 backdrop-blur-sm rounded-xl p-4">
                  <div className="text-2xl font-bold text-white">{stats.totalDestinations}</div>
                  <div className="text-blue-100 text-sm">Destinations</div>
                </div>
                <div className="bg-white/10 backdrop-blur-sm rounded-xl p-4">
                  <div className="text-2xl font-bold text-white">{favorites.length}</div>
                  <div className="text-blue-100 text-sm">Favorites</div>
                </div>
              </div>
            )}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl lg:text-4xl font-bold text-gray-900 mb-4">
              Why Choose WanderMind?
            </h2>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              We combine cutting-edge AI technology with comprehensive travel data to make your trip planning effortless and exciting.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => {
              const IconComponent = feature.icon;
              return (
                <div
                  key={index}
                  className="text-center p-6 rounded-2xl hover:shadow-lg transition-all duration-300 group hover:-translate-y-1"
                >
                  <div className={`inline-flex p-4 rounded-2xl ${feature.bg} ${feature.color} mb-4 group-hover:scale-110 transition-transform duration-300`}>
                    <IconComponent className="h-8 w-8" />
                  </div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-2">
                    {feature.title}
                  </h3>
                  <p className="text-gray-600">
                    {feature.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Popular Destinations Section */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between mb-12">
            <div>
              <h2 className="text-3xl lg:text-4xl font-bold text-gray-900 mb-4">
                Popular Destinations
              </h2>
              <p className="text-xl text-gray-600">
                Discover the most loved destinations by our community
              </p>
            </div>
            <Link href="/destinations">
              <Button variant="outline" icon={ArrowRight}>
                View All Destinations
              </Button>
            </Link>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {isLoadingDestinations ? (
              Array.from({ length: 6 }).map((_, index) => (
                <DestinationCardSkeleton key={index} />
              ))
            ) : (
              popularDestinations.map((destination) => (
                <DestinationCard
                  key={destination.id}
                  destination={destination}
                  isFavorite={favorites.some(fav => fav.id === destination.id)}
                  onFavoriteToggle={handleFavoriteToggle}
                  showWeather={true}
                  variant="featured"
                />
              ))
            )}
          </div>
        </div>
      </section>

      {/* Statistics Section */}
      <section className="py-20 bg-gradient-to-r from-primary-600 to-travel-600">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl lg:text-4xl font-bold text-white mb-4">
              Trusted by Travelers Worldwide
            </h2>
            <p className="text-xl text-blue-100">
              Join thousands of happy travelers who trust WanderMind for their adventures
            </p>
          </div>

          <div className="grid grid-cols-2 lg:grid-cols-4 gap-8">
            {stats_display.map((stat, index) => {
              const IconComponent = stat.icon;
              return (
                <div key={index} className="text-center">
                  <div className="inline-flex p-4 rounded-2xl bg-white/10 backdrop-blur-sm mb-4">
                    <IconComponent className="h-8 w-8 text-white" />
                  </div>
                  <div className="text-3xl lg:text-4xl font-bold text-white mb-2">
                    {stat.value}
                  </div>
                  <div className="text-blue-100 text-lg">
                    {stat.label}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl lg:text-4xl font-bold text-gray-900 mb-4">
              What Our Travelers Say
            </h2>
            <p className="text-xl text-gray-600">
              Real stories from real travelers who found their perfect adventures
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <div
                key={index}
                className="bg-gray-50 rounded-2xl p-6 hover:shadow-lg transition-all duration-300 group hover:-translate-y-1"
              >
                <div className="flex items-center space-x-1 mb-4">
                  {Array.from({ length: testimonial.rating }).map((_, i) => (
                    <Star key={i} className="h-5 w-5 text-yellow-400 fill-yellow-400" />
                  ))}
                </div>
                
                <blockquote className="text-gray-700 mb-6 italic">
                  "{testimonial.text}"
                </blockquote>
                
                <div className="flex items-center space-x-3">
                  <img
                    src={testimonial.avatar}
                    alt={testimonial.name}
                    className="w-12 h-12 rounded-full object-cover"
                  />
                  <div>
                    <div className="font-semibold text-gray-900">
                      {testimonial.name}
                    </div>
                    <div className="text-sm text-gray-500">
                      {testimonial.location}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-br from-gray-900 to-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-3xl lg:text-4xl font-bold text-white mb-6">
              Ready to Start Your Next Adventure?
            </h2>
            <p className="text-xl text-gray-300 mb-8">
              Join WanderMind today and let AI help you create the perfect travel experience tailored just for you.
            </p>
            
            <div className="flex flex-col sm:flex-row items-center justify-center space-y-4 sm:space-y-0 sm:space-x-6">
              {isAuthenticated ? (
                <>
                  <Link href="/trips/create">
                    <Button variant="primary" size="lg" icon={Sparkles}>
                      Create Your First Trip
                    </Button>
                  </Link>
                  <Link href="/destinations">
                    <Button variant="outline" size="lg" className="border-gray-600 text-white hover:bg-gray-700">
                      Explore Destinations
                    </Button>
                  </Link>
                </>
              ) : (
                <>
                  <Link href="/auth/register">
                    <Button variant="primary" size="lg" icon={ArrowRight}>
                      Sign Up Free
                    </Button>
                  </Link>
                  <Link href="/auth/login">
                    <Button variant="outline" size="lg" className="border-gray-600 text-white hover:bg-gray-700">
                      Sign In
                    </Button>
                  </Link>
                </>
              )}
            </div>

            <p className="text-gray-400 text-sm mt-6">
              No credit card required • Free forever • Start planning in minutes
            </p>
          </div>
        </div>
      </section>
    </Layout>
  );
};

export default HomePage;