# Generated by Django 5.2.5 on 2025-09-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='weather_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
