# Generated by Django 5.2.5 on 2025-09-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_delete_review'),
        ('trips', '0002_trip_weather_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.AddField(
            model_name='trip',
            name='destinations',
            field=models.ManyToManyField(related_name='trips', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(default='Untitled Trip', max_length=255),
            preserve_default=False,
        ),
    ]
