# Generated by Django 5.2.5 on 2025-09-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_review_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
